name: GRMS CI releases

on:
  push:
    branches: 
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          xargs sudo apt-get install -y < apt-requirements.txt
          ./zcutil/build.sh -j$(nproc)
          zip --junk-paths grms-cli-linux src/grmsd src/grms-cli
      - name: Upload grms-cli-linux.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: grms-cli-linux
          path: ./grms-cli-linux.zip

  windows-build:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build (Windows)
        if: runner.os == 'Linux'
        run: |
          xargs sudo apt-get install -y < apt-requirements.txt
          ./zcutil/build-win.sh -j$(nproc)
          zip --junk-paths grms-cli-windows src/grmsd.exe src/grms-cli.exe
      - name: Upload grms-cli-windows.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: grms-cli-windows
          path: ./grms-cli-windows.zip

  publish-release:
    name: Publishing CI release
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs: [linux-build, windows-build]
    steps:
      - name: Download grms-cli-linux.zip
        uses: actions/download-artifact@v4
        with:
          name: grms-cli-linux  

      - name: Download grms-cli-windows.zip
        uses: actions/download-artifact@v4
        with:
          name: grms-cli-windows  

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Shortify commit sha
        id: shortify_commit
        shell: bash
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cd_release_${{ steps.shortify_commit.outputs.sha_short }}_${{ steps.extract_branch.outputs.branch }}
          name: CD Release ${{ steps.shortify_commit.outputs.sha_short }} ${{ steps.extract_branch.outputs.branch }}
          draft: false
          prerelease: true
          files: |
            ./grms-cli-linux.zip
            ./grms-cli-windows.zip
