name: GRMS CI releases

on:
  push:
    branches: 
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          xargs sudo apt-get install -y < apt-requirements.txt
          ./zcutil/build.sh -j$(nproc)
          zip --junk-paths grms-cli-linux src/grmsd src/grms-cli
      - name: Upload grms-cli-linux.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: grms-cli-linux
          path: ./grms-cli-linux.zip

  windows-build:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build (Windows)
        if: runner.os == 'Linux'
        run: |
          xargs sudo apt-get install -y < apt-requirements.txt
          ./zcutil/build-win.sh -j$(nproc)
          zip --junk-paths grms-cli-windows src/grmsd.exe src/grms-cli.exe
      - name: Upload grms-cli-windows.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: grms-cli-windows
          path: ./grms-cli-windows.zip

  macos-build:
    name: MacOS Build
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Clean up binaries and links (macOS)
        run: |
          rm -f /usr/local/bin/2to3-3.*
          rm -f /usr/local/bin/idle3.*
          rm -f /usr/local/bin/pydoc3.*
          rm -f /usr/local/bin/python3.*
          rm -f /usr/local/bin/2to3
          rm -f /usr/local/bin/idle3
          rm -f /usr/local/bin/pydoc3
          rm -f /usr/local/bin/python3
          rm -f /usr/local/bin/python3-config
      
      - name: Install deps (macOS)
        run: |
          brew update
          brew tap discoteq/discoteq; brew install flock
          brew install autoconf autogen automake
          brew install binutils
          brew install protobuf
          brew install coreutils
          brew install wget
          brew install python3
          brew install zip

      - name: Build (macOS)
        run: |
          ./zcutil/build-mac-arm.sh -j4
          cd src
          zip --junk-paths ../grms-cli-macos.zip grmsd grms-cli grms-tx

      - name: Upload grms-cli-macos.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: grms-cli-macos
          path: ./grms-cli-macos.zip
            
  publish-release:
    name: Publishing CI release
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs: [linux-build, windows-build, macos-build]
    steps:
      - name: Download grms-cli-linux.zip
        uses: actions/download-artifact@v4
        with:
          name: grms-cli-linux  

      - name: Download grms-cli-windows.zip
        uses: actions/download-artifact@v4
        with:
          name: grms-cli-windows

      - name: Download grms-cli-macos.zip
        uses: actions/download-artifact@v4
        with:
          name: grms-cli-macos

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Shortify commit sha
        id: shortify_commit
        shell: bash
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cd_release_${{ steps.shortify_commit.outputs.sha_short }}_${{ steps.extract_branch.outputs.branch }}
          name: CD Release ${{ steps.shortify_commit.outputs.sha_short }} ${{ steps.extract_branch.outputs.branch }}
          draft: false
          prerelease: true
          files: |
            ./grms-cli-linux.zip
            ./grms-cli-windows.zip
            ./grms-cli-macos.zip