name: GRMS aarch64

on:
  push:
    branches: 
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          # Обновляем репозитории
          sudo apt-get update
          
          # Установка необходимых пакетов для кросс-компиляции
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            linux-libc-dev-arm64-cross \
            m4 \
            autoconf \
            g++-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu \
            libtool \
            ncurses-dev \
            unzip \
            git \
            zlib1g-dev \
            wget \
            bsdmainutils \
            automake \
            curl \
            # Добавляем библиотеки для zstd
            libzstd-dev:arm64 \
            zstd \
            libzstd1:arm64 \
            # Дополнительные библиотеки, которые могут понадобиться
            libssl-dev:arm64 \
            libssh2-1-dev:arm64 \
            librtmp-dev:arm64 \
            libidn2-dev:arm64 \
            libpsl-dev:arm64 \
            libnghttp2-dev:arm64 \
            libbrotli-dev:arm64 \
            libgsasl7-dev:arm64 \
            libkrb5-dev:arm64 \
            libldap2-dev:arm64
          
          # Проверяем наличие библиотеки zstd для aarch64
          ls -la /usr/aarch64-linux-gnu/lib/*zstd* || echo "Файлы zstd не найдены"
          
          # Сборка
          HOST=aarch64-linux-gnu ./zcutil/build.sh -j$(nproc)
          
          # Создание архива
          zip --junk-paths grms-cli-aarch64-linux src/grmsd src/grms-cli
      
      - name: Upload grms-cli-aarch64-linux.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: grms-cli-aarch64-linux
          path: ./grms-cli-aarch64-linux.zip
