name: Verus CI releases

on:
  push:
    branches:
    - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          xargs sudo apt-get install -y < apt-requirements.txt
          ./zcutil/build.sh -j$(nproc)
          zip --junk-paths verus-linux src/verusd src/verus
      - name: Upload verus-linux.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: verus-linux
          path: ./verus-linux.zip

  windows-build:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build (Windows)
        if: runner.os == 'Linux'
        run: |
          xargs sudo apt-get install -y < apt-requirements.txt
          ./zcutil/build-win.sh -j$(nproc)
          zip --junk-paths verus-windows src/verusd.exe src/verus.exe
      - name: Upload verus-windows.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: verus-windows
          path: ./verus-windows.zip

  publish-release:
    name: Publishing CI release
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs: [linux-build, windows-build]
    steps:
      - name: Download verus-linux.zip
        uses: actions/download-artifact@v4
        with:
          name: verus-linux  

      - name: Download verus-windows.zip
        uses: actions/download-artifact@v4
        with:
          name: verus-windows  

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Shortify commit sha
        id: shortify_commit
        shell: bash
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cd_release_${{ steps.shortify_commit.outputs.sha_short }}_${{ steps.extract_branch.outputs.branch }}
          name: CD Release ${{ steps.shortify_commit.outputs.sha_short }} ${{ steps.extract_branch.outputs.branch }}
          draft: false
          prerelease: true
          files: |
            ./verus-linux.zip
            ./verus-windows.zip
